### ISSUE TITLE
access code not used anywhere

### ISSUE THREAD

**Issue by morekapil** [nitishkumarsingh13/node-ccavenue#1]
![ccavenue](https://cloud.githubusercontent.com/assets/14902485/10187852/ee1680fe-6778-11e5-9009-f7672e4588df.png)
Hi,
Tried to use your module to integrate ccavenue payment gateway. However  I see that the module doesnt use access_code anywhere. The new ccavenue api needs access code and working key both. added a screenshot pic from ccavenue website

**Comment by nitishk1316** [comment]
It is still working without access code.

What is the issue your are facing ?

**Comment by nitishk1316** [comment]
without access code it is working.
