### ISSUE TITLE
developer account

### ISSUE THREAD

**Issue by himanshugoyal5734** [nitishkumarsingh13/node-ccavenue#3]
hello sir ,is there any sandbox account in ccavenue for testing purpose ???

**Comment by nitishk1316** [comment]
There is no sandbox account.

But you can use dummy card number 4111 1111 1111 1111 to test for a unsuccessful transaction.

This things in mentioned in CCAVenueWorldIntegrationManual pdf.

Read this:
https://world.ccavenue.com/downloads/CCAVenueWorldIntegrationManual.pdf
