### ISSUE TITLE
Redirect URl Error in ccavenue

### ISSUE THREAD

**Issue by KalaiselvanMahendran** [nitishkumarsingh13/node-ccavenue#4]
Getting Type Error while using POST method to get redirect url in nodejs and angularjs

```
TypeError: Not a string or buffer
    at TypeError (native)
    at Decipher.Cipher.update (crypto.js:140:26)
    at Object.decrypt (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\ccavenue\helper.js:5:24)
```

```
router.post('/redirect-url', function response(req, res) {
        // console.log(req);
        var data = ccavenue.paymentRedirect(req); //It will get response from ccavenue payment. 
        console.log(data);
        if(data.isCheckSumValid === true && data.AuthDesc == 'Y') {
            console.log('Success' + res);
            // Success 
            // Your code 
        } else if(data.isCheckSumValid === true && data.AuthDesc == 'N') {
            console.log('UnSuccess' + res);
            // Unuccessful 
            // Your code 
        } else if(data.isCheckSumValid === true && data.AuthDesc == 'B') {
            // Batch processing mode 
            // Your code 
        } else {
            // Illegal access 
            // Your code 
        }
    });
```

**Comment by nitishk1316** [comment]
I think 'text' parameter value is empty.

Can you check and let me know

**Comment by KalaiselvanMahendran** [comment]
You mean order_id, amount, and basic info of customer ???

**Comment by nitishk1316** [comment]
var data = ccavenue.paymentRedirect(req);
Here
req.body.encResponse is empty or not a property.

Check what your getting in req ?

**Comment by KalaiselvanMahendran** [comment]
if i try this 

```
router.post('/redirect-url', function response(req, res) {
        console.log(req.body.encResponse);
    });
```

am getting Undefined.

if i try this 

```
router.post('/redirect-url', function response(req, res) {
        var data = ccavenue.paymentRedirect(req); //It will get response from ccavenue payment. 
        console.log(req.body.encResponse);
    });
```

Am getting this error

> TypeError: Not a string or buffer
>     at TypeError (native)
>     at Decipher.Cipher.update (crypto.js:140:26)
>     at Object.decrypt (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\ccavenue\helper.js:5:24)
>     at Object.paymentRedirect (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\ccavenue\index.js:71:27)
>     at response (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\server\app\routes\book.js:22:25)
>     at Layer.handle [as handle_request](C:Usersexcrin-L1KalaiProjectsWhizzrdDemonode_modulesexpresslibrouterlayer.js:95:5)
>     at next (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\express\lib\router\route.js:131:13)
>     at Route.dispatch (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\express\lib\router\route.js:112:3)
>     at Layer.handle [as handle_request](C:Usersexcrin-L1KalaiProjectsWhizzrdDemonode_modulesexpresslibrouterlayer.js:95:5)
>     at C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\express\lib\router\index.js:277:22
>     at Function.process_params (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\express\lib\router\index.js:330:12)
>     at next (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\express\lib\router\index.js:271:10)
>     at Function.handle (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\express\lib\router\index.js:176:3)
>     at router (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\express\lib\router\index.js:46:12)
>     at Layer.handle [as handle_request](C:Usersexcrin-L1KalaiProjectsWhizzrdDemonode_modulesexpresslibrouterlayer.js:95:5)
>     at trim_prefix (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\express\lib\router\index.js:312:13)
>     at C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\express\lib\router\index.js:280:7
>     at Function.process_params (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\express\lib\router\index.js:330:12)
>     at next (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\express\lib\router\index.js:271:10)
>     at serveStatic (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\express\node_modules\serve-static\index.js:74:16)
>     at Layer.handle [as handle_request](C:Usersexcrin-L1KalaiProjectsWhizzrdDemonode_modulesexpresslibrouterlayer.js:95:5)
>     at trim_prefix (C:\Users\excrin-L1\KalaiProjects\WhizzrdDemo\node_modules\express\lib\router\index.js:312:13)

**Comment by KalaiselvanMahendran** [comment]
make-payment not redirecting to ccavenue page

**Comment by KalaiselvanMahendran** [comment]
getting this error in 
Error Code: 90
Error Description:  Required+parameter+is+missing+or+Invalid+session.%3CB+style%3D%22color%3Ared%22%3EKindly+clear+cache+of+browser+and+re-initiate+your+transaction%3C%2FB%3E
in ccavenue

**Comment by sumit7274** [comment]
i m getting this error
"Cannot find name 'router'.
"
