### ISSUE TITLE
How we can pass different currency

### ISSUE THREAD

**Issue by Akash0333** [nitishkumarsingh13/node-ccavenue#8]
How we can pass different currency

**Comment by nitishk1316** [comment]
Pass Currency as a object key with value CURRENCY_CODE in ccavenue.setOtherParams(param); 

For Example:
var param = {
  Currency: 'USD', 
  billing_cust_name: 'Nitish Kumar',
  key_name: value  //add other key values
};
ccavenue.setOtherParams(param); //Set Customer Info
