### ISSUE TITLE
CCAvenue Transaction Error Page

### ISSUE THREAD

**Issue by Akash0333** [nitishkumarsingh13/node-ccavenue#9]
Hello me getting this error can you please help me 
![screen shot 2017-03-17 at 5 53 30 pm](https://cloud.githubusercontent.com/assets/13021367/24043058/aeb99dbc-0b3a-11e7-8875-c5b84229f8e5.png)

**Comment by pankajbansal** [comment]
Hi @Akash0333 

How you resolved this?
I am also getting the same error.

**Comment by pankajbansal** [comment]
@nitishkumarsingh13 

Can you help me to resolve this issue?
